#!/bin/bash

echo "** BUILD start"
echo "* Creating logstamp"
LOGSTAMP_DATE=`date "+%Y-%m-%d %H:%M:%S"`
echo "* Contents: $LOGSTAMP_DATE $BITBUCKET_DEPLOYMENT_ENVIRONMENT $BITBUCKET_COMMIT"
echo "$LOGSTAMP_DATE $BITBUCKET_DEPLOYMENT_ENVIRONMENT $BITBUCKET_COMMIT" > .logstamp

# We need PHP 7.1.
update-alternatives --set php /usr/bin/php7.1

echo "* Zipping 'n' movin'"

composer install
npm install

npx grunt build
npx grunt zip

mkdir -p wp-content/plugins
mv releases/*.zip wp-content/plugins/
cd wp-content/plugins/
unzip *.zip
rm *.zip

echo "** BUILD end"
