#!/bin/bash

echo "** Deployment: START"

echo "* Preparing version control for deployment push"
rm .gitignore
mv .build/gitignore-wpengine .gitignore

echo "* Resetting git"
rm -fr .git
git init

git add .
git commit -m "Bitbucket Pipelines Deployment"
git clean -f

echo "* Adding git remote: $WPE_INSTALL"
git config --global user.name "Bitbucket Pipelines Deploy"
git config --global user.email "$EMAIL"
git remote add wpe git@git.wpengine.com:production/$WPE_INSTALL.git


echo "* Pushing $BITBUCKET_BRANCH to $WPE_INSTALL"
git status
git push wpe HEAD:$BITBUCKET_BRANCH --force

echo "** Deployment: END"
